server:
  port: 8189
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product_track?currentSchema=java_app
    username: [локальный_username укажешь]
    password: [локальный_password укажешь]
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true
  thymeleaf:
    encoding: UTF-8
